### ISSUE TITLE
JSON parsing error.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#162]
**Describe the bug**

> Hypar shows "One or more errors occurred. (Unexpected character
> encountered while parsing value: P. Path '', line 0, position 0.)",
> and the div has a title of "at
> System.Threading.Tasks.Task`1.GetResultCore(Boolean
> waitCompletionNotification),at lambda_method(Closure , Stream , Stream
> , LambdaContextInternal )". I have no ideas on this one, haven't look
> into it at all.

**To Reproduce**

**Expected behavior**
Expected function to execute without exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/33582525/60535573-6f8baa00-9cd2-11e9-89b6-9a27b104d7c6.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by ikeough** [comment]
Stack trace:
```
One or more errors occurred. (Unexpected character encountered while parsing value: P. Path '', line 0, position 0.): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Hypar.Functions.Execution.AWS.S3ModelStore.GetModelAsync(String executionId)
at Hypar.Functions.Execution.InvocationWrapper`2.InvokeAsync(TInput input)
at Mass.Function.Handler(MassInputs args, ILambdaContext context) in C:\Users\aahau\GitHub\Mass\src\Function.g.cs:line 27
```

**Comment by mattc** [comment]
Ah, interesting. I've only seen this when a function is being re-executed, and only for a short time (perhaps until Lambda shutdown). Could it be holding onto the original execution ID and reading the previous run's output?

**Comment by ikeough** [comment]
There was definitely some re-use of state in the previous version of the `S3ModelStore`. This has been fixed in the latest release. I'd be interested to see if these throw the same error with the updated lib.

**Comment by hummingburd** [comment]
So far this morning I haven't encountered this error again. Obviously I'll be banging on the system for the next several days. Stay tuned.

**Comment by ikeough** [comment]
Is that with the newest version of Hypar.Functions?

**Comment by hummingburd** [comment]
No, as it turns out. 2.17, not 2.18. I'll upgrade.

**Comment by mattc** [comment]
No relevant changes were in 2.18. There's a solid chance that Ian's past Function changes actually fixed the issue for you.
