### ISSUE TITLE
Grid.U.DivideByApproximateLength yields division by 0 error.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#248]
**Describe the bug**
For `Grid.V.DivideByApproximateLength`, if the length specified is larger than the size of the bounding box of the polygon, you get the following error:
```
Stack Trace:
       at Elements.Spatial.Grid1d.DivideByCount(Int32 n) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Spatial/Grid1d.cs:line 248
   at Elements.Spatial.Grid1d.DivideByApproximateLength(Double targetLength, EvenDivisionMode divisionMode) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Spatial/Grid1d.cs:line 285
   at Elements.Analysis.AnalysisMesh..ctor(Polygon perimeter, Int32 uLength, Int32 vLength, Color startColor, Color endColor, Func`2 analyze, Guid id, String name) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Analysis/AnalysisMesh.cs:line 80
   at Elements.Tests.AnalysisMeshTests.AnalysisMesh() in /Users/ikeough/Documents/Hypar/Hypar/Elements/test/Elements.Tests/AnalysisMeshTests.cs:line 29
```

**Comment by andrewheumann** [comment]
fixed in https://github.com/hypar-io/Elements/commit/367651c0ea037844edac3e5f91ab00c4c2ec8735
