### ISSUE TITLE
Self-intersecting polygon fails to generate a Solid

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#274]
Self intersecting polygons should be rejected during construction.

```
There was an error executing the function.
One or more errors occurred. (Index was outside the bounds of the array.)
Index was outside the bounds of the array.
   at Elements.Geometry.Solids.Solid.Tessellate(Byte[]& vertexBuffer, Byte[]& indexBuffer, Byte[]& normalBuffer, Byte[]& colorBuffer, Byte[]& uvBuffer, Double[]& vmax, Double[]& vmin, Double[]& nmin, Double[]& nmax, Single[]& cmin, Single[]& cmax, UInt16& imin, UInt16& imax, Double[]& uvmin, Double[]& uvmax) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Geometry/Solids/Solid.cs:line 418
   at Elements.Serialization.glTF.GltfExtensions.ProcessSolid(Solid solid, String id, String materialName, Gltf& gltf, Dictionary`2& materials, List`1& buffer, List`1 bufferViews, List`1 accessors, List`1 meshes, List`1 lines, Boolean drawEdges, Transform t) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Serialization/glTF/GltfExtensions.cs:line 938
   at Elements.Serialization.glTF.GltfExtensions.GetRenderDataForElement(Element e, Gltf gltf, Dictionary`2 materials, List`1 buffer, List`1 bufferViews, List`1 accessors, List`1 meshes, List`1 nodes, Dictionary`2 meshElementMap, List`1 lines, Boolean drawEdges) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Serialization/glTF/GltfExtensions.cs:line 773
   at Elements.Serialization.glTF.GltfExtensions.InitializeGlTF(Model model, List`1 buffer, Boolean drawEdges) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Serialization/glTF/GltfExtensions.cs:line 693
   at Elements.Serialization.glTF.GltfExtensions.SaveGlb(Model model, String path, Boolean drawEdges) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Serialization/glTF/GltfExtensions.cs:line 603
   at Elements.Serialization.glTF.GltfExtensions.ToGlTF(Model model, String path, Boolean useBinarySerialization, Boolean drawEdges) in /Users/ikeough/Documents/Hypar/Hypar/Elements/src/Elements/Serialization/glTF/GltfExtensions.cs:line 50
   at Hypar.Functions.Execution.Local.FileModelStore`1.SetModelAsync(Targs args, Model model) in /Users/ikeough/Documents/Hypar/Hypar/Functions/src/Execution/Local/FileModelStore.cs:line 77
   at Hypar.Functions.Execution.InvocationWrapper`2.InvokeAsync(TInput input)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Hypar.Commands.RunCommand.ExecuteFunction(String functionDir, WeakReference& alcWeakRef) in /Users/ikeough/Documents/Hypar/Hypar/CLI/src/Commands/RunCommand.cs:line 476
```

**Comment by ikeough** [comment]
Self intersection is checked in the validator during Polygon construction.
