### ISSUE TITLE
Beam Start/End Extensions

### ISSUE THREAD

**Issue by johnpierson** [hypar-io/Elements#534]
**Describe the bug**
While working through element converters for Beams I found that the Start and End Setbacks are in fact just setbacks. Negative values result in the following error:
```
2021-02-25 14:57:19.403 -07:00 [DBG] Failed to convert selection to Hypar.
System.Exception: The parameter t must be between 0.0 and 1.0.
   at Elements.Geometry.Line.PointAt(Double u)
   at Elements.Geometry.Line.TransformAt(Double u)
   at Elements.Geometry.Curve.Frames(Double startSetback, Double endSetback)
   at Elements.Geometry.Solids.Solid.SweepFaceAlongCurve(Polygon perimeter, IList`1 holes, ICurve curve, Double startSetback, Double endSetback)
   at Elements.Geometry.Kernel.CreateSweepAlongCurve(Profile profile, Curve curve, Double startSetback, Double endSetback)
   at Elements.Validators.SweepValidator.UpdateGeometry(Sweep sweep)
   at Elements.Validators.SweepValidator.PostConstruct(Object obj)
   at Elements.Geometry.Solids.Sweep..ctor(Profile profile, Curve curve, Double startSetback, Double endSetback, Double profileRotation, Boolean isVoid)
   at Elements.StructuralFraming.UpdateRepresentations()
   at Elements.Model.ToJson(Boolean indent)
   at Hypar.Revit.ExtractHyparModel.SaveModel(Model model)
   at Hypar.Revit.ExtractHyparModel.ExtractSelectedElements(Document document, ICollection`1 elementIds)
   at Hypar.Revit.ConvertSelectionToHypar.Execute(ExternalCommandData commandData, String& message, ElementSet elements)
```
Thinking about it more, it makes sense since the name is **Setback**. However, this is confusing when translating from Revit as beams can also be extended further as cantilevered. Negative would result in a cutback beam.

**To Reproduce**
1. Define a beam with a negative value for setback (possible in Revit).
2. View log.

**Expected behavior**
I think for now I will just work around this using the beam curve and only taking negative values from Revit. I do see an issue when we go from HYPAR -> Revit though as the curve that represents the beam will be different than where it was derived from.

**Images**

This one shows my concern regarding translation.
![image](https://user-images.githubusercontent.com/15744724/109226290-b669c580-777b-11eb-8c9c-ae35d6869b02.png)

**Comment by wynged** [comment]
Very interesting observation, I don't think we ever considered the case where the cantilever action was applied as a negative setback.  This functionality should be possible, but will require thinking about how we find a point that is outside of a curve.  In the case of a line this is not to hard, but for an arc for example, is the extension tangential to the endpoint, or is it as if the curve continued with the same arc....  

While we should take some queues from Revit regarding how elements are represented, I don't think we need to worry too much about the round trip scenario, as objects that originated in Revit are not likely candidates for re-import, and if they are then we are likely trying to "fix" them so perfect fidelity is not actually the goal.  Definitely good for testing purposes though.

**Comment by ikeough** [comment]
That error is correct. Although we've made updates to the treatment of curves recently, we still enforce that the setbacks are setbacks and not extensions. The setbacks are also just visual setbacks, like Revit. The working line of the beam continues to be the beam's curve. If you really want a cantilever, I recommend using some of the other geometric tools to extend the beam's curve.
