### ISSUE TITLE
ToGlTF() fails if Model is created with user-specified Dictionary rather than AddElement...

### ISSUE THREAD

**Issue by daniel-fink** [hypar-io/Elements#611]
**Describe the bug**
See title

**To Reproduce**
Given a user specifying their own `Element`s in a `Model`, and converting it to glTF like this:
```
var space = new Elements.Space(new Profile(Polygon.Rectangle(10, 10)), 10);
var elements = new Dictionary<Guid, Element>();
elements.Add(Guid.NewGuid(), space);

var model = new Elements.Model(new Transform(0,0,0), elements);
var gltf = model.ToGlTF();
```

`.ToGlTF()` fails with the following report:
```
System.Collections.Generic.KeyNotFoundException : The given key 'mass' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Elements.Serialization.glTF.GltfExtensions.ProcessSolidsAsCSG(GeometricElement geometricElement, String id, String materialName, Gltf& gltf, Dictionary`2& materials, List`1& buffer, List`1 bufferViews, List`1 accessors, List`1 meshes, List`1 lines, Transform t)
   at Elements.Serialization.glTF.GltfExtensions.ProcessGeometricRepresentation(Element e, Gltf& gltf, Dictionary`2& materialIndexMap, List`1& buffers, List`1 bufferViews, List`1 accessors, List`1 meshes, List`1 nodes, Dictionary`2 meshElementMap, List`1 lines, Boolean drawEdges, String materialName, Int32& meshId, GeometricElement geometricElement)
   at Elements.Serialization.glTF.GltfExtensions.GetRenderDataForElement(Element e, Gltf gltf, Dictionary`2 materialIndexMap, List`1 buffers, List`1 allBuffers, List`1 schemaBuffers, List`1 bufferViews, List`1 accessors, List`1 materials, List`1 textures, List`1 images, List`1 samplers, List`1 meshes, List`1 nodes, Dictionary`2 meshElementMap, Dictionary`2 nodeElementMap, Dictionary`2 meshTransformMap, List`1 lines, Boolean drawEdges)
   at Elements.Serialization.glTF.GltfExtensions.InitializeGlTF(Model model, List`1& allBuffers, Boolean drawEdges)
   at Elements.Serialization.glTF.GltfExtensions.ToGlTF(Model model)
```

**Expected behavior**
Instead if the `Model` is created with`.AddElement()` like this:
```
model.AddElement(space);
```

Then `.ToGlTF()` is successful.

**Comment by ikeough** [comment]
Thanks @daniel-fink. I believe this error comes from the mass material not being available during glTF creation. `AddElement` is a kind of magical method that takes care of finding all the elements that are referenced by an element and adding them to the model's internal dictionary as well. This includes things like `Profile` and `Material` objects. The constructor which takes a dictionary must have all of these other associated elements in it as well or you'll see failures like the one you're describing. 

We can do a better job of handling that error by dropping back to the default material if the material you expect is not found.

**Comment by andrewheumann** [comment]
@ikeough We should probably also make the model constructors that take a dictionary `private` — the user should never expect to be able to construct the dictionary themselves. In the above example, a material fallback wouldn't solve the whole issue — the `Profile` of the `Space` would be missing, too. It's easy to take `Model(Transform @transform, System.Collections.Generic.IDictionary<Guid, Element> @elements)` private — but we'll have to figure out something clever for the `Model(Position @origin, Transform @transform, System.Collections.Generic.IDictionary<Guid, Element> @elements)` constructor generated from the schema (or just stop generating it from a schema).

**Comment by daniel-fink** [comment]
Agree with @andrewheumann -- problem here is the silent failure mode; a user may not know they have an ill-formed `Model` until running a specific operation...
